name: 🧪 Tests (Nix)

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  stack:
    name: 🖥️  ${{ matrix.os }} ❄️  Nix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: 📤 Checkout
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: cachix/install-nix-action@v13
      name: ❄️  Set up Nix
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: actions/cache@v2
      name: 🗄️  Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-stack-nix-ci-4

    - name: 🧪 Test
      run: |
        stack test --nix
