name: Continuous Integration

on:
  push: { "branches": [ "master" ] }
  pull_request: { "branches": [ "master" ] }

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: 📥 Checkout repository
      uses: actions/checkout@v1

    - name: 🔑 Cache Key
      id: cache_key
      run: echo ::set-output name=key::$(md5sum stack.yaml | awk '{print $1}')

    - name: 💾 Cache Dependencies
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ steps.cache_key.outputs.key }}

    - name: 📸 Build Snapshot
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        stack --no-terminal test --fast --bench --only-snapshot

    - name: 🔨 Build & Test
      run: |
        stack --no-terminal test --fast
